Traceback (most recent call last):
  File "C:\Users\Charith\anaconda3\Lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\Users\Charith\anaconda3\Lib\site-packages\nbclient\client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Charith\anaconda3\Lib\site-packages\jupyter_core\utils\__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Charith\anaconda3\Lib\asyncio\base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Charith\anaconda3\Lib\site-packages\nbclient\client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "C:\Users\Charith\anaconda3\Lib\site-packages\nbclient\client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\Charith\anaconda3\Lib\site-packages\nbclient\client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Import packages
import pandas as pd # package for reading in and manipulating data
from datetime import datetime # package for manipulating dates
from sklearn.model_selection import train_test_split # package for splitting data

import utils # utility functions defined for this lab

print('All packages imported successfully!')
------------------


[1;31m---------------------------------------------------------------------------[0m
[1;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [1;32mIn[1], line 6[0m
[0;32m      3[0m [38;5;28;01mfrom[39;00m [38;5;21;01mdatetime[39;00m [38;5;28;01mimport[39;00m datetime [38;5;66;03m# package for manipulating dates[39;00m
[0;32m      4[0m [38;5;28;01mfrom[39;00m [38;5;21;01msklearn[39;00m[38;5;21;01m.[39;00m[38;5;21;01mmodel_selection[39;00m [38;5;28;01mimport[39;00m train_test_split [38;5;66;03m# package for splitting data[39;00m
[1;32m----> 6[0m [38;5;28;01mimport[39;00m [38;5;21;01mutils[39;00m [38;5;66;03m# utility functions defined for this lab[39;00m
[0;32m      8[0m [38;5;28mprint[39m([38;5;124m'[39m[38;5;124mAll packages imported successfully![39m[38;5;124m'[39m)

File [1;32m~\OneDrive - Cardiff University\CodeWork\Artificial-Intelligence-for-Sensor-Data-Book\parts\part10\C1\AirQualityDesignPhase\utils.py:11[0m
[0;32m      9[0m [38;5;28;01mimport[39;00m [38;5;21;01mipywidgets[39;00m [38;5;28;01mas[39;00m [38;5;21;01mwidgets[39;00m
[0;32m     10[0m [38;5;28;01mfrom[39;00m [38;5;21;01mipywidgets[39;00m [38;5;28;01mimport[39;00m interact
[1;32m---> 11[0m [38;5;28;01mimport[39;00m [38;5;21;01mtensorflow[39;00m [38;5;28;01mas[39;00m [38;5;21;01mtf[39;00m
[0;32m     12[0m [38;5;28;01mfrom[39;00m [38;5;21;01mtensorflow[39;00m [38;5;28;01mimport[39;00m keras
[0;32m     13[0m [38;5;28;01mfrom[39;00m [38;5;21;01mtensorflow[39;00m[38;5;21;01m.[39;00m[38;5;21;01mkeras[39;00m [38;5;28;01mimport[39;00m layers

[1;31mModuleNotFoundError[0m: No module named 'tensorflow'

